export const initialState = {
  pieces: [
    {id: 1, type: 'pawn', color: 'white', position: [0,1], captured: false},
    {id: 2, type: 'pawn', color: 'white', position: [1,1]},
    {id: 3, type: 'pawn', color: 'white', position: [2,1]},
    {id: 4, type: 'pawn', color: 'white', position: [3,1]},
    {id: 5, type: 'pawn', color: 'white', position: [4,1]},
    {id: 6, type: 'pawn', color: 'white', position: [5,1]},
    {id: 7, type: 'pawn', color: 'white', position: [6,1]},
    {id: 8, type: 'pawn', color: 'white', position: [7,1]},
    {id: 9, type: 'pawn', color: 'black', position: [0,6]},
    {id: 10, type: 'pawn', color: 'black', position: [1,6]},
    {id: 11, type: 'pawn', color: 'black', position: [2,6]},
    {id: 12, type: 'pawn', color: 'black', position: [3,6]},
    {id: 13, type: 'pawn', color: 'black', position: [4,6]},
    {id: 14, type: 'pawn', color: 'black', position: [5,6]},
    {id: 15, type: 'pawn', color: 'black', position: [6,6]},
    {id: 16, type: 'pawn', color: 'black', position: [7,6]},
    {id: 18, type: 'rook', color: 'white', position: [7,0]},
    {id: 17, type: 'rook', color: 'white', position: [0,0]},
    {id: 19, type: 'rook', color: 'black', position: [0,7]},
    {id: 20, type: 'rook', color: 'black', position: [7,7]},
    {id: 21, type: 'knight', color: 'white', position: [6,0], captured: false},
    {id: 22, type: 'knight', color: 'white', position: [1,0]},
    {id: 23, type: 'knight', color: 'black', position: [1,7]},
    {id: 24, type: 'knight', color: 'black', position: [6,7]},
    {id: 25, type: 'bishop', color: 'white', position: [5,0]},
    {id: 26, type: 'bishop', color: 'white', position: [2,0]},
    {id: 27, type: 'bishop', color: 'black', position: [2,7]},
    {id: 29, type: 'bishop', color: 'black', position: [5,7]},
    {id: 30, type: 'queen', color: 'black', position: [3,7]},
    {id: 31, type: 'queen', color: 'white', position: [3,0]},
    {id: 32, type: 'king', color: 'black', position: [4,7]},
    {id: 33, type: 'king', color: 'white', position: [4,0]},
  ],
squares: [
  {id: 57, position: {x: 0, y: 7}, name: 'a8', selected: false, occupied: true},
  {id: 58, position: {x: 1, y: 7}, name: 'b8', selected: true, occupied: true},
  {id: 59, position: {x: 2, y: 7}, name: 'c8', selected: false, occupied: true},
  {id: 60, position: {x: 3, y: 7}, name: 'd8', selected: false, occupied: true},
  {id: 61, position: {x: 4, y: 7}, name: 'e8', selected: false, occupied: true},
  {id: 62, position: {x: 5, y: 7}, name: 'f8', selected: false, occupied: true},
  {id: 63, position: {x: 6, y: 7}, name: 'g8', selected: false, occupied: true},
  {id: 64, position: {x: 7, y: 7}, name: 'h8', selected: false, occupied: true},
  {id: 49, position: {x: 0, y: 6}, name: 'a7', selected: false, occupied: true},
  {id: 50, position: {x: 1, y: 6}, name: 'b7', selected: false, occupied: true},
  {id: 51, position: {x: 2, y: 6}, name: 'c7', selected: false, occupied: true},
  {id: 52, position: {x: 3, y: 6}, name: 'd7', selected: false, occupied: true},
  {id: 53, position: {x: 4, y: 6}, name: 'e7', selected: false, occupied: true},
  {id: 54, position: {x: 5, y: 6}, name: 'f7', selected: false, occupied: true},
  {id: 55, position: {x: 6, y: 6}, name: 'g7', selected: false, occupied: true},
  {id: 56, position: {x: 7, y: 6}, name: 'h7', selected: false, occupied: true},
  {id: 41, position: {x: 0, y: 5}, name: 'a6', selected: false, occupied: false},
  {id: 42, position: {x: 1, y: 5}, name: 'b6', selected: false, occupied: false},
  {id: 43, position: {x: 2, y: 5}, name: 'c6', selected: false, occupied: false},
  {id: 44, position: {x: 3, y: 5}, name: 'd6', selected: false, occupied: false},
  {id: 45, position: {x: 4, y: 5}, name: 'e6', selected: false, occupied: false},
  {id: 46, position: {x: 5, y: 5}, name: 'f6', selected: false, occupied: false},
  {id: 47, position: {x: 6, y: 5}, name: 'g6', selected: false, occupied: false},
  {id: 48, position: {x: 7, y: 5}, name: 'h6', selected: false, occupied: false},
  {id: 33, position: {x: 0, y: 4}, name: 'a5', selected: false, occupied: false},
  {id: 34, position: {x: 1, y: 4}, name: 'b5', selected: false, occupied: false},
  {id: 35, position: {x: 2, y: 4}, name: 'c5', selected: false, occupied: false},
  {id: 36, position: {x: 3, y: 4}, name: 'd5', selected: false, occupied: false},
  {id: 37, position: {x: 4, y: 4}, name: 'e5', selected: false, occupied: false},
  {id: 38, position: {x: 5, y: 4}, name: 'f5', selected: false, occupied: false},
  {id: 39, position: {x: 6, y: 4}, name: 'g5', selected: false, occupied: false},
  {id: 40, position: {x: 7, y: 4}, name: 'h5', selected: false, occupied: false},
  {id: 25, position: {x: 0, y: 3}, name: 'a4', selected: false, occupied: false},
  {id: 26, position: {x: 1, y: 3}, name: 'b4', selected: false, occupied: false},
  {id: 27, position: {x: 2, y: 3}, name: 'c4', selected: false, occupied: false},
  {id: 28, position: {x: 3, y: 3}, name: 'd4', selected: false, occupied: false},
  {id: 29, position: {x: 4, y: 3}, name: 'e4', selected: false, occupied: false},
  {id: 30, position: {x: 5, y: 3}, name: 'f4', selected: false, occupied: false},
  {id: 31, position: {x: 6, y: 3}, name: 'g4', selected: false, occupied: false},
  {id: 32, position: {x: 7, y: 3}, name: 'h4', selected: false, occupied: false},
  {id: 17, position: {x: 0, y: 2}, name: 'a3', selected: false, occupied: false},
  {id: 18, position: {x: 1, y: 2}, name: 'b3', selected: false, occupied: false},
  {id: 19, position: {x: 2, y: 2}, name: 'c3', selected: false, occupied: false},
  {id: 20, position: {x: 3, y: 2}, name: 'd3', selected: false, occupied: false},
  {id: 21, position: {x: 4, y: 2}, name: 'e3', selected: false, occupied: false},
  {id: 22, position: {x: 5, y: 2}, name: 'f3', selected: false, occupied: false},
  {id: 23, position: {x: 6, y: 2}, name: 'g3', selected: false, occupied: false},
  {id: 24, position: {x: 7, y: 2}, name: 'h3', selected: false, occupied: false},
  {id: 9, position: {x: 0, y: 1}, name: 'a2', selected: false, occupied: true},
  {id: 10, position: {x: 1, y: 1}, name: 'b2', selected: false, occupied: true},
  {id: 11, position: {x: 2, y: 1}, name: 'c2', selected: false, occupied: true},
  {id: 12, position: {x: 3, y: 1}, name: 'd2', selected: false, occupied: true},
  {id: 13, position: {x: 4, y: 1}, name: 'e2', selected: false, occupied: true},
  {id: 14, position: {x: 5, y: 1}, name: 'f2', selected: false, occupied: true},
  {id: 15, position: {x: 6, y: 1}, name: 'g2', selected: false, occupied: true},
  {id: 16, position: {x: 7, y: 1}, name: 'h2', selected: false, occupied: true},
  {id: 1, position: {x: 0, y: 0}, name: 'a1', selected: false, occupied: true},
  {id: 2, position: {x: 1, y: 0}, name: 'b1', selected: false, occupied: true},
  {id: 3, position: {x: 2, y: 0}, name: 'c1', selected: false, occupied: true},
  {id: 4, position: {x: 3, y: 0}, name: 'd1', selected: false, occupied: true},
  {id: 5, position: {x: 4, y: 0}, name: 'e1', selected: false, occupied: true},
  {id: 6, position: {x: 5, y: 0}, name: 'f1', selected: false, occupied: true},
  {id: 7, position: {x: 6, y: 0}, name: 'g1', selected: false, occupied: true},
  {id: 8, position: {x: 7, y: 0}, name: 'h1', selected: false, occupied: true},
],
  numberOfMoves: 0
};
