export const initialState = {
  pieces: [
    {id: 1, type: 'pawn', color: 'white', position: [0,6]},
    {id: 2, type: 'pawn', color: 'white', position: [1,6]},
    {id: 3, type: 'pawn', color: 'white', position: [2,6]},
    {id: 4, type: 'pawn', color: 'white', position: [3,6]},
    {id: 5, type: 'pawn', color: 'white', position: [4,6]},
    {id: 6, type: 'pawn', color: 'white', position: [5,6]},
    {id: 7, type: 'pawn', color: 'white', position: [6,6]},
    {id: 8, type: 'pawn', color: 'white', position: [7,6]},
    {id: 9, type: 'pawn', color: 'black', position: [0,1]},
    {id: 10, type: 'pawn', color: 'black', position: [1,1]},
    {id: 11, type: 'pawn', color: 'black', position: [2,1]},
    {id: 12, type: 'pawn', color: 'black', position: [3,1]},
    {id: 13, type: 'pawn', color: 'black', position: [4,1]},
    {id: 14, type: 'pawn', color: 'black', position: [5,1]},
    {id: 15, type: 'pawn', color: 'black', position: [6,1]},
    {id: 16, type: 'pawn', color: 'black', position: [7,1]},
    {id: 18, type: 'rook', color: 'white', position: [7,7]},
    {id: 17, type: 'rook', color: 'white', position: [0,7]},
    {id: 19, type: 'rook', color: 'black', position: [0,0]},
    {id: 20, type: 'rook', color: 'black', position: [7,0]},
    {id: 21, type: 'knight', color: 'white', position: [6,7]},
    {id: 22, type: 'knight', color: 'white', position: [1,7]},
    {id: 23, type: 'knight', color: 'black', position: [1,0]},
    {id: 24, type: 'knight', color: 'black', position: [6,0]},
    {id: 25, type: 'bishop', color: 'white', position: [5,7]},
    {id: 26, type: 'bishop', color: 'white', position: [2,7]},
    {id: 27, type: 'bishop', color: 'black', position: [2,0]},
    {id: 28, type: 'bishop', color: 'black', position: [5,0]},
    {id: 25, type: 'queen', color: 'black', position: [3,0]},
    {id: 26, type: 'queen', color: 'white', position: [3,7]},
    {id: 27, type: 'king', color: 'black', position: [4,0]},
    {id: 28, type: 'king', color: 'white', position: [4,7]},
  ],
  hasMoved: false
};
